{% set name = "pyeit" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/liubenyuan/pyEIT/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 388fce68478862cb574e829faabf34089ffda95410d8852cba95e1b176f56cbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - shapely

test:
  imports:
    - pyeit
  source_files:
    - tests/*.py
  commands:
    - pytest tests/
  requires:
    - pytest

about:
  home: https://github.com/liubenyuan/pyEIT
  summary: A Python based framework for EIT (Electrical Impedance Tomography)
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - liubenyuan
