{% set name = "pyeit" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/liubenyuan/pyEIT/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 428827222428625638c99e1e1d6beb006320298f066010cbf064e36498fe43db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - shapely

test:
  imports:
    - pyeit
  source_files:
    - tests/*.py
  commands:
    - pytest tests/
  requires:
    - pytest

about:
  home: https://github.com/liubenyuan/pyEIT
  summary: A Python based framework for EIT (Electrical Impedance Tomography)
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - liubenyuan
